
package com.dl.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DlWebServiceService", targetNamespace = "http://webservice.dl.com/", wsdlLocation = "http://127.0.0.1:8888/dlws?wsdl")
public class DlWebServiceImpl
    extends Service
{

    private final static URL DLWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DLWEBSERVICESERVICE_EXCEPTION;
    private final static QName DLWEBSERVICESERVICE_QNAME = new QName("http://webservice.dl.com/", "DlWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8888/dlws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DLWEBSERVICESERVICE_WSDL_LOCATION = url;
        DLWEBSERVICESERVICE_EXCEPTION = e;
    }

    public DlWebServiceImpl() {
        super(__getWsdlLocation(), DLWEBSERVICESERVICE_QNAME);
    }

    public DlWebServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), DLWEBSERVICESERVICE_QNAME);
    }

    public DlWebServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, DLWEBSERVICESERVICE_QNAME);
    }

    public DlWebServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DLWEBSERVICESERVICE_QNAME);
    }

    public DlWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DlWebServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DlWebService
     */
    @WebEndpoint(name = "DlWebServicePort")
    public DlWebService getDlWebServicePort() {
        return super.getPort(new QName("http://webservice.dl.com/", "DlWebServicePort"), DlWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DlWebService
     */
    @WebEndpoint(name = "DlWebServicePort")
    public DlWebService getDlWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.dl.com/", "DlWebServicePort"), DlWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DLWEBSERVICESERVICE_EXCEPTION!= null) {
            throw DLWEBSERVICESERVICE_EXCEPTION;
        }
        return DLWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
